version: "3.6"

services:
  app:
    build: .
    volumes:
      - .:/usr/src/app
      - ~/config:/root/config
    ports:
      - "3030:3030"
    command: sh -c "npm run dev"
    environment:
      NODE_ENV: development